import { describe, expect, it } from "vitest";
import {
  cleanSessionPreview,
  compactProjectPath,
  formatElapsed,
  formatSessionLine,
  isNoisePreview,
} from "./session-list-format.js";

describe("compactProjectPath", () => {
  it("shows repo tail segments", () => {
    expect(
      compactProjectPath(
        "/tmp/workspace/src/gitlab.example.com/rock/goblin-sorting",
      ),
    ).toBe("rock/goblin-sorting");
    expect(
      compactProjectPath("/tmp/workspace/src/gitlab.example.com/shzf/hermes"),
    ).toBe("shzf/hermes");
  });
});

describe("cleanSessionPreview", () => {
  it("filters caveat noise", () => {
    expect(
      isNoisePreview(
        "Caveat: The messages below were generated by the user while running local comman",
      ),
    ).toBe(true);
    expect(cleanSessionPreview("fix login bug")).toBe("fix login bug");
  });
});

describe("formatElapsed", () => {
  it("秒级", () => {
    expect(formatElapsed(45_000)).toBe("45 秒");
  });

  it("分秒级", () => {
    expect(formatElapsed(3 * 60_000 + 20_000)).toBe("3 分 20 秒");
  });

  it("小时分钟级", () => {
    expect(formatElapsed(60 * 60_000 + 5 * 60_000)).toBe("1 小时 5 分");
  });
});

describe("formatSessionLine", () => {
  it("renders multi-line blocks", () => {
    const text = formatSessionLine(
      {
        id: "e4e50b15-aaaa-bbbb-cccc-ddddeeeeffff",
        backend: "claude",
        cwd: "/tmp/workspace/src/gitlab.example.com/rock/goblin-sorting",
        preview: "检查分拣拦截逻辑",
        updatedAt: "2026-06-29T06:38:38.000Z",
      },
      4,
      true,
    );
    expect(text).toContain("**5.**");
    expect(text).toContain("rock/goblin-sorting");
    expect(text).toContain("检查分拣拦截逻辑");
    expect(text.split("\n")).toHaveLength(2);
  });
});
