import { describe, expect, it } from "vitest";
import {
  cleanSessionPreview,
  compactProjectPath,
  formatSessionLine,
  isNoisePreview,
} from "./session-list-format.js";

describe("compactProjectPath", () => {
  it("shows repo tail segments", () => {
    expect(
      compactProjectPath(
        "/tmp/workspace/src/gitlab.example.com/rock/goblin-sorting",
      ),
    ).toBe("rock/goblin-sorting");
    expect(
      compactProjectPath("/tmp/workspace/src/gitlab.example.com/shzf/hermes"),
    ).toBe("shzf/hermes");
  });
});

describe("cleanSessionPreview", () => {
  it("filters caveat noise", () => {
    expect(
      isNoisePreview(
        "Caveat: The messages below were generated by the user while running local comman",
      ),
    ).toBe(true);
    expect(cleanSessionPreview("fix login bug")).toBe("fix login bug");
  });
});

describe("formatSessionLine", () => {
  it("renders multi-line blocks", () => {
    const text = formatSessionLine(
      {
        id: "e4e50b15-aaaa-bbbb-cccc-ddddeeeeffff",
        backend: "claude",
        cwd: "/tmp/workspace/src/gitlab.example.com/rock/goblin-sorting",
        preview: "检查分拣拦截逻辑",
        updatedAt: "2026-06-29T06:38:38.000Z",
      },
      4,
      true,
    );
    expect(text).toContain("**5.**");
    expect(text).toContain("rock/goblin-sorting");
    expect(text).toContain("检查分拣拦截逻辑");
    expect(text.split("\n")).toHaveLength(2);
  });
});
